.\" Manpage for yahtsee.
.\" Contact c0der78@gmail.com to correct errors or typos.
.TH man 1 "08 Jan 2015" "0.1" "yahtsee man page"
.SH NAME
yahtsee \- play a game of yahtsee
.SH SYNOPSIS
yahtsee
.SH DESCRIPTION
yahtsee is a dice rolling game that can be played with up to 6 other players.
.SH OPTIONS
'sb' : score best      'k3' : score three of a kind 
's1' : score aces      'k4' : score four of a kind
's2' : score twos      'f'  : score full house
's3' : score threes    't4' : score small straight
's4' : score fours     't5' : score large straight
's5' : score fives     'y'  : score yahtzee 
's6' : score sixes     'c'  : score chance
'r'  : roll dice       'n'  : new game
'q' or 'escape' : quit
↑ ↓  : cycle views     ← →  : cycle cards
.SH BUGS
No known bugs at this time.
.SH AUTHOR
Ryan Jennings (c0der78@gmail.com)
